version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: >-
    npm install

artifacts:
- path: code.zip
  name: code

deploy:
- provider: Environment
  name: test
  on:
    branch: master