version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: >-
    npm install
    echo %appveyor_build_version%
    type code.zip
# artifacts:
# - path: /deploy
#   name: code

deploy:
- provider: Environment
  name: test
  artifact: code.zip
  on:
    branch: master