version: 1.0.{build}
image: Visual Studio 2017
build_script:
- sh: >-
    npm install

    console.log("I am getting printed")
artifacts:
- path: /
  name: code
deploy:
- provider: Environment
  name: test
  on:
    branch: master