version: 1.0.{build}
image: Visual Studio 2017
build_script:
#  - echo %appveyor_build_version%
#  - type code.zip
 - cmd: >-
    npm install
#  - echo %appveyor_build_version%  
artifacts:
- path: /

deploy:
- provider: Environment
  name: test
#   artifact: code.zip
  
  on:
    branch: master