version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: npm install
artifacts:
- path: /
  name: code

for:

# QA
-
  branches:
    only:
      - master

  deploy:
  - provider: AzureAppServiceZipDeploy
    website: bss-app
    username: $bss-app
    password:
      secure: 8zDkDoJQKdgwVl9/R9NOSTk4xcwwO3oA8yUDj80wdVsHS0kOBLqKmP1Q2pqInof0+FMZsqZgo9OYpaymU50Ynw==
    artifact: code.zip